import React, { useState } from 'react';
import { Copy, Share2, Ban, Flag, Check } from 'lucide-react';
import { ScanResult } from '../types';

interface ActionButtonsProps {
  result: ScanResult;
}

function generateWarningText(result: ScanResult): string {
  const lines = [
    `ScamGuard AI Alert`,
    `Risk Level: ${result.riskLevel} (${result.confidence}% confidence)`,
    ``,
    `Recommendation: ${result.advice}`,
  ];
  if (result.reasons.length > 0) {
    lines.push('', 'Detection Details:');
    result.reasons.forEach(r => lines.push(`- ${r}`));
  }
  lines.push('', `Scanned text: "${result.input.slice(0, 200)}${result.input.length > 200 ? '...' : ''}"`);
  return lines.join('\n');
}

function generateReportText(result: ScanResult): string {
  const date = new Date(result.timestamp).toLocaleString();
  const lines = [
    `=== SCAM REPORT ===`,
    `Generated by ScamGuard AI`,
    `Date: ${date}`,
    ``,
    `RISK LEVEL: ${result.riskLevel}`,
    `CONFIDENCE: ${result.confidence}%`,
    ``,
    `RECOMMENDATION:`,
    result.advice,
    ``,
    `FINDINGS:`,
  ];
  result.reasons.forEach(r => lines.push(`  - ${r}`));
  lines.push(
    ``,
    `ORIGINAL MESSAGE:`,
    `"${result.input}"`,
    ``,
    `=== END OF REPORT ===`
  );
  return lines.join('\n');
}

const ActionButtons: React.FC<ActionButtonsProps> = ({ result }) => {
  const [copiedWarning, setCopiedWarning] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);
  const [blocked, setBlocked] = useState(false);

  const handleCopyWarning = async () => {
    const text = generateWarningText(result);
    try {
      await navigator.clipboard.writeText(text);
      setCopiedWarning(true);
      setTimeout(() => setCopiedWarning(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopiedWarning(true);
      setTimeout(() => setCopiedWarning(false), 2000);
    }
  };

  const handleShare = async () => {
    const text = generateWarningText(result);
    if (navigator.share) {
      try {
        await navigator.share({ title: 'ScamGuard AI Alert', text });
      } catch {
        // User cancelled share
      }
    } else {
      await navigator.clipboard.writeText(text);
      setCopiedWarning(true);
      setTimeout(() => setCopiedWarning(false), 2000);
    }
  };

  const handleBlock = () => {
    setBlocked(true);
  };

  const handleReport = async () => {
    const text = generateReportText(result);
    try {
      await navigator.clipboard.writeText(text);
      setCopiedReport(true);
      setTimeout(() => setCopiedReport(false), 2000);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopiedReport(true);
      setTimeout(() => setCopiedReport(false), 2000);
    }
  };

  const btnBase =
    'flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 border';

  return (
    <div className="space-y-3">
      <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Actions</h3>
      <div className="grid grid-cols-2 gap-2">
        <button
          onClick={handleCopyWarning}
          className={`${btnBase} ${
            copiedWarning
              ? 'bg-green-500/20 border-green-500/50 text-green-400'
              : 'bg-slate-800/70 border-slate-700 text-slate-300 hover:bg-slate-700/70 hover:border-slate-600'
          }`}
        >
          {copiedWarning ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          {copiedWarning ? 'Copied!' : 'Copy Warning'}
        </button>

        <button
          onClick={handleShare}
          className={`${btnBase} bg-slate-800/70 border-slate-700 text-slate-300 hover:bg-slate-700/70 hover:border-slate-600`}
        >
          <Share2 className="w-4 h-4" />
          Share Alert
        </button>

        <button
          onClick={handleBlock}
          disabled={blocked}
          className={`${btnBase} ${
            blocked
              ? 'bg-red-500/20 border-red-500/50 text-red-400 cursor-default'
              : 'bg-slate-800/70 border-slate-700 text-slate-300 hover:bg-red-500/20 hover:border-red-500/50 hover:text-red-400'
          }`}
        >
          <Ban className="w-4 h-4" />
          {blocked ? 'Blocked' : 'Block Number'}
        </button>

        <button
          onClick={handleReport}
          className={`${btnBase} ${
            copiedReport
              ? 'bg-green-500/20 border-green-500/50 text-green-400'
              : 'bg-slate-800/70 border-slate-700 text-slate-300 hover:bg-orange-500/20 hover:border-orange-500/50 hover:text-orange-400'
          }`}
        >
          {copiedReport ? <Check className="w-4 h-4" /> : <Flag className="w-4 h-4" />}
          {copiedReport ? 'Report Copied!' : 'Report Scam'}
        </button>
      </div>
    </div>
  );
};

export default ActionButtons;
